# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:22
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num_equipos', models.PositiveIntegerField(default=0, null=True)),
                ('publica', models.BooleanField(default=True)),
                ('fecha_real_inicio', models.DateTimeField(null=True)),
                ('fecha_ficticia_inicio', models.DateTimeField(null=True)),
                ('factor_tiempo', models.PositiveIntegerField(default=1)),
                ('sexo_permitido', models.PositiveIntegerField(default=0)),
                ('permitir_bots', models.BooleanField(default=True)),
                ('inteligencia_bots', models.PositiveIntegerField(default=3, null=True)),
                ('tipo_avance_jornadas', models.PositiveIntegerField(default=0)),
                ('dinero_inicial', models.IntegerField(default=20000, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('num_jugadores_inicial', models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('nivel_max_jugadores_inicio', models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Usuario')),
            ],
        ),
    ]
