# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:24
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributosVariablesJugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('ofertado', models.BooleanField(default=False)),
                ('ataque', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('defensa', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('velocidad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('pases', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('anotacion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('portero', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('resistencia', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('agresividad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('concentracion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('estabilidad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('moral', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('altura', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)])),
                ('peso', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_equipo.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apodo', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('color_piel', models.CharField(max_length=30)),
                ('color_pelo', models.CharField(max_length=30)),
                ('color_ojos', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='atributosvariablesjugador',
            name='jugador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='gestion_jugador.Jugador'),
        ),
    ]
