# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('numero', models.PositiveIntegerField()),
                ('jugada', models.BooleanField(default=False)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.Liga')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
