# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:22
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_liga', '__first__'),
        ('gestion_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=3)),
                ('dinero', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.Liga')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuario.Usuario')),
            ],
        ),
    ]
