# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_jornada', '0001_initial'),
        ('gestion_equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionEquipoJornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_favor', models.PositiveIntegerField(default=0)),
                ('goles_contra', models.PositiveIntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_equipo.Equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_jornada.Jornada')),
            ],
        ),
    ]
