# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_jugador', '0001_initial'),
        ('gestion_partido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suceso',
            name='jugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_jugador.Jugador'),
        ),
        migrations.AlterField(
            model_name='suceso',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_equipo.Equipo'),
        ),
    ]
