# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:29
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_jugador', '0001_initial'),
        ('gestion_equipo', '0001_initial'),
        ('gestion_liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('puja', models.PositiveIntegerField(default=1)),
                ('precio_compra', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('atributos_jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_jugador.AtributosVariablesJugador')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subastas_como_comprador', to='gestion_equipo.Equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.Liga')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas_como_vendedor', to='gestion_equipo.Equipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
