# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_jugador', '0001_initial'),
        ('gestion_jornada', '0001_initial'),
        ('gestion_equipo', '0001_initial'),
        ('gestion_liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlineacionEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_equipo.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('BA', 'BANQUILLO'), ('PO', 'PORTERO'), ('DF', 'DEFENSA'), ('CC', 'CENTROCAMPISTA'), ('DL', 'DELANTERO')], max_length=2)),
                ('atributos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_jugador.AtributosVariablesJugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('alineacion_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlineacionLocal', to='gestion_partido.AlineacionEquipo')),
                ('alineacion_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlineacionVisitante', to='gestion_partido.AlineacionEquipo')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Local', to='gestion_equipo.Equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitante', to='gestion_equipo.Equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_jornada.Jornada')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.Liga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_partido', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.PositiveIntegerField(choices=[(100, 'Comienza equipo'), (101, 'Fin de la parte'), (102, 'Tiempo de descuento'), (200, 'Movimiento del balon'), (201, 'Contrataque'), (300, 'Regate'), (301, 'Pase'), (400, 'Disparo'), (666, 'Gol')])),
                ('valor', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_equipo.Equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_partido.Partido')),
            ],
        ),
        migrations.AddField(
            model_name='alineacionequipo',
            name='jugadores',
            field=models.ManyToManyField(blank=True, to='gestion_partido.JugadorPartido'),
        ),
    ]
